application: luletrafik
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: PIL
  version: "1.1.7"

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'
  
- url: /static
  static_dir: static

- url: /.*
  script: main.application

env_variables:
  DJANGO_SETTINGS_MODULE: 'luletrafik.settings'